version: '3.8'

services:
  agentic-security:
    build: .
    volumes:
      - .:/app
      - .security_cache:/app/.security_cache
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - SLACK_WEBHOOK=${SLACK_WEBHOOK}
    depends_on:
      - zap

  zap:
    image: owasp/zap2docker-stable
    command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
    ports:
      - "8080:8080"
