[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
port = 8501
address = "localhost"
maxUploadSize = 200
enableCORS = true
enableXsrfProtection = true

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[runner]
magicEnabled = true

[client]
showErrorDetails = true
toolbarMode = "auto"
