name: Security Pipeline

on:
  schedule:
    - cron: '0 5 * * *'  # Daily at 5 AM
  workflow_dispatch:

jobs:
  security-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io unzip
          pip install --user -r requirements.txt

      - name: Install Aider
        run: pip install --user aider-chat

      - name: Run security pipeline
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          ./run_pipeline.sh

      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated security fixes
          branch: security-fixes
          title: 'Security: Automated fixes for vulnerabilities'
          body: 'Automated security fixes applied by Agentic Security pipeline'
          labels: security, automated
